# Generated by Django 4.2.16 on 2024-10-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_lesson_amount"),
        ("users", "0004_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.course",
                verbose_name="Оплата курса",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.lesson",
                verbose_name="Оплата урока",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_summa",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
