# Generated by Django 4.2.16 on 2024-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_summa",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Сумма оплаты в рублях"
            ),
        ),
    ]
