# Generated by Django 4.2.16 on 2024-09-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_course_preview_alter_lesson_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
