# Generated by Django 4.2.16 on 2024-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Стоимость урока"),
        ),
    ]
